'use strict';
const GoalTypes = {
  EACH_COLOR_2: 'EACH_COLOR_2',
  TWO_PAIRS: 'TWO_PAIRS',
  FULL_HOUSE: 'FULL_HOUSE',
  SAME_COLOR_3: 'SAME_COLOR_3',
  SAME_COLOR_4: 'SAME_COLOR_4',
  SAME_COLOR_5: 'SAME_COLOR_5',
  IDENTICAL_CARDS_3: 'IDENTICAL_CARDS_3',
  IDENTICAL_CARDS_4: 'IDENTICAL_CARDS_4',
  IDENTICAL_CARDS_5: 'IDENTICAL_CARDS_5',
  OUT_3: 'OUT_3',
  UNIQUE_OUT_CARDS_3: 'UNIQUE_OUT_CARDS_3',
  UNIQUE_OUT_CARDS_4: 'UNIQUE_OUT_CARDS_4',
  BASES_3: 'BASES_3',
  BASES_RBI_4: 'BASES_RBI_4',
  BASES_SEQ_3: 'BASES_SEQ_3',
  UNKNOWN: 'UNKNOWN'
};

export default GoalTypes;